SET SERVEROUTPUT ON;
create or replace procedure CustomerTransaction (
TXNTYPE IN TRANSACTION.txn_type%TYPE,
custId IN TRANSACTION.customer_id%TYPE,
STOCKID	IN TRANSACTION.stock_id%TYPE,
QTY IN TRANSACTION.qty%TYPE,
PRICE	IN TRANSACTION.price%TYPE
)
AS
p_buyingpower NUMBER(10,0);
s_co_id NUMBER(10,0);
result1 VARCHAR2(50) := NULL;
max_ID NUMBER(10);
vcSecName VARCHAR2(30);
nExchgID NUMBER(10);
SUMPRICE NUMBER(10);
e_LOW_BUYINGPOWER EXCEPTION;
E_INCORRECT_CUSTID EXCEPTION;
BEGIN
SELECT cust_buyingpower INTO p_buyingpower FROM CUSTOMER WHERE CUST_ID=custId;

-----GENERATING TRANSACTION ID-------
select (MAX(TXN_ID)+1) into max_ID from TRANSACTION;
dbms_output.put_line('View Stock Purchase guide');

dbms_output.put_line(' STOCK       QUANTITY       PRICE');
------CHECKING BUYING POWER------------
SELECT QTY*PRICE INTO SUMPRICE FROM DUAL;
IF(p_buyingpower<SUMPRICE)
THEN
RAISE e_LOW_BUYINGPOWER;
END IF;



-----INSERT INTO TRANSACTION----------
INSERT INTO TRANSACTION (TXN_ID, TXN_TYPE, CUSTOMER_ID, STOCK_ID, QTY,PRICE,TXN_DATE,TXN_TIME)
    VALUES(max_ID,TXNTYPE,custId,STOCKID,QTY,PRICE,SYSDATE ,SYSTIMESTAMP);
    
    COMMIT;
     dbms_output.put_line('TRANSACTION SUCCESFUL');
 --- UPDATE BUYING POWER------
 UPDATE  CUSTOMER SET CUST_BUYINGPOWER=CUST_BUYINGPOWER-SUMPRICE WHERE CUST_ID=custId;
 
 COMMIT;

 dbms_output.put_line('HERE IS A LIST OF PREVIOUS TRANSACTION');
 FOR PREVIOUSTRANSACTION IN 
          (
            SELECT TXN_TYPE,STOCK_ID,QTY,PRICE  FROM transaction 
          )
          LOOP
            dbms_output.put_line(PREVIOUSTRANSACTION.TXN_TYPE||'-------'|| PREVIOUSTRANSACTION.STOCK_ID||'------ '||PREVIOUSTRANSACTION.QTY||'-------'||PREVIOUSTRANSACTION.PRICE);
          END LOOP;
EXCEPTION
WHEN 
e_LOW_BUYINGPOWER THEN
dbms_output.put_line('NOT ENOUGH BUYING POWER');
END;
/
SELECT * FROM CUSTOMER;
EXEC CustomerTransaction('B',1,1,5,100);