---VIEW ALL SHARES---
CREATE OR REPLACE VIEW ALL_SHARES AS
SELECT CS.SEC_DESC AS SECURITY_NAME, SI.MARKET_VAL FROM 
(select stock_id,market_val from
(SELECT stock_id,market_val, rank() over (partition by stock_id order by as_of_date desc) as rank from stockinfo)
stock_curr 
where stock_curr.rank=1) SI
join COMPANYSECURITY CS
on  CS.SECURITY_ID = SI.STOCK_ID;

SELECT * FROM ALL_SHARES;

---VIEW MY SHARES---
CREATE OR REPLACE VIEW MY_SHARES AS
SELECT CP.COMPANY_NAME, H.QTY, H.ASOFDATE "AS_OF_DATE"
FROM CUSTOMER C JOIN CUSTOMERHOLDING H
ON C.CUST_ID = H.CUSTOMERID
JOIN COMPANY CP
ON H.COMPANYID = CP.COMPANY_ID
where UPPER(C.CUST_USERNAME) =(SELECT username FROM user_users);

SELECT * FROM MY_SHARES;